# gateway
spring:
  cloud:
    gateway:
      routes:
        - id: site-mgt-service
          uri: lb://SITEMGT-SERVICE
          predicates:
            - Path=/sitemgt-service/**
          filters:
            - RewritePath=/sitemgt-service/(?<segment>.*), /$\{segment}
        - id: inference-service
          predicates:
            - Path=/fr-api-service/**
          uri: lb://FR-API-SERVICE
          filters:
            - RewritePath=/fr-api-service/(?<segment>.*), /$\{segment}

