
server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth-service/**
        - id: facesdk-service
          uri: lb://FACESDK-SERVICE
          predicates:
            - Path=/facesdk-service/**
        - id: inference-service
          predicates:
            - Path=/inference-service/**
          uri: lb://INFERENCE-SERVICE
          filters:
            - RewritePath=/inference-service/(?<path>.*),/$\{path}
           
