# gateway
spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 200
      default-filters:
        - name: Retry
          args:
            retries: 3
            statuses: INTERNAL_SERVER_ERROR
            methods: POST,GET,PATCH,PUT,DELETE,OPTIONS
            backoff:
              firstBackoff: 10ms
              maxBackoff: 50ms
              factor: 2
              basedOnPreviousValue: false
      routes:
        - id: sitemgt-service
          uri: lb://SITEMGT-SERVICE
          predicates:
            - Path=/sitemgt-service/**
          filters:
            - RewritePath=/sitemgt-service/(?<segment>.*), /$\{segment}
        - id: inference-service
          predicates:
            - Path=/fr-api-service/**
          uri: lb://FR-API-SERVICE
          filters:
            - RewritePath=/fr-api-service/(?<segment>.*), /$\{segment}
        - id: device-service
          predicates:
            - Path=/device-service/**
          uri: lb://DEVICE-SERVICE
          filters:
            - RewritePath=/device-service/(?<segment>.*), /$\{segment}
        - id: audit-service
          predicates:
            - Path=/audit-service/**
          uri: lb://AUDIT-SERVICE
          filters:
            - RewritePath=/audit-service/(?<segment>.*), /$\{segment}
        - id: comm-service
          predicates:
            - Path=/comm-service/**
          uri: lb://COMM-SERVICE
          filters:
            - RewritePath=/comm-service/(?<segment>.*), /$\{segment}
        - id: payment-service
          predicates:
            - Path=/payment-service/**
          uri: lb://PAYMENT-SERVICE
          filters:
            - RewritePath=/payment-service/(?<segment>.*), /$\{segment}

