# gateway
spring:
  cloud:
    gateway:
      routes:
        - id: site-mgt-service
          uri: lb://SITEMGT-SERVICE
          predicates:
            - Path=/sitemgt-service/**
        - id: facesdk-service
          uri: lb://FACESDK-SERVICE
          predicates:
            - Path=/facesdk-service/**
        - id: inference-service
          predicates:
            - Path=/inference-service/**
          uri: lb://GO-SERVICE
          filters:
            - RewritePath=/inference-service/(?<segment>.*), /$\{segment}

